[tool.isort]
profile = 'google'
line_length = 120
lines_after_imports = 2
order_by_type = false
force_single_line = false
force_sort_within_sections = false
skip='l5kit\/data\/proto'
known_first_party='l5kit'

[tool.pytest.ini_options]
xfail_strict=true